# coding: utf-8
#
# Copyright (C) 2015 Gil Mendes <gil00mendes@gmail.com>
#

from util import FeatureSources
Import('config', 'env')

sources = FeatureSources(config, [

])

# Define o linker script a ser usado
env['LDSCRIPT'] = env.LDScript('link.ld', 'link.ld.in')

Return('sources')
