# coding: utf-8
#
# Copyright (C) 2015 Gil Mendes <gil00mendes@gmail.com>
#

Import('config', 'manager')

# Gera o header de configurações.
f = open('config.h', 'w')
f.write('/* Este ficheiro é gerado automaticamente, não edite. */\n\n')
for (k, v) in config.items():
    if isinstance(v, str):
        f.write("#define CONFIG_%s \"%s\"\n" % (k, v))
    elif isinstance(v, bool):
        if v:
            f.write("#define CONFIG_%s 1\n" % (k))
    elif isinstance(v, int):
        f.write("#define CONFIG_%s %d\n" % (k, int(v)))
    else:
        raise Exception, "Unsupported type %s in config" % (type(v))
f.close()

dist = manager['dist']

##########
# Kernel #
##########

# constroi o kernel
SConscript(dirs = ['kernel'])

# We place the final output binaries in a single directory.
#env['OUTDIR'] = Dir('bin')